version: '3'
services:
  app:
    image: soli0222/ai:latest
    platform: linux/amd64
    volumes:
      - './config.json:/ai/config.json:ro'
      - './font.ttf:/ai/font.ttf:ro'
      - './data:/ai/data'
    restart: always
